apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app: cert-manager
    catagory: certificates
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    chart: cert-manager
    targetRevision: v1.19.2
    helm:
      values: |
        crds:
          enabled: true
